sentence = input("Enter a sentence: ")
words = sentence.split()
print("Original:", sentence)
print("Length:", len(sentence))
print("Without spaces:", len(sentence.replace(" ", "")))
print("Word count:", len(words))
print("Uppercase:", sentence.upper())
print("Lowercase:", sentence.lower())
print("Title:", sentence.title())
print("First word:", words[0])
print("Last word:", words[-1])
print("Reverse:", sentence[::-1])
